// <auto-generated />
namespace SalesManagement_SysDev.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class phoreinkey6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(phoreinkey6));
        
        string IMigrationMetadata.Id
        {
            get { return "202012100432302_phoreinkey6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
